### ISSUE TITLE
add  abhack  0.0.3  pls

### ISSUE THREAD

**Issue by doihi** [Smug2f/Fast-Client-Archive#10]

**Comment by Smug2f** [comment]
I dont have

**Comment by doihi** [comment]
https://github.com/LLPLLQxw/ABHACK/releases 
safe?

**Comment by Smug2f** [comment]
The fact that abhack 0.0.3 has less size than 0.0.1 and the fact that it is **uploaded two years ago in 2022 instead of 2023 for 0.0.1** release just indicate that its an older version or not abhack , i wouldnt run or store this
