### ISSUE TITLE
Wheres rushercrack 1.3.1

### ISSUE THREAD

**Issue by Jebacka** [Smug2f/Fast-Client-Archive#2]

**Comment by Smug2f** [comment]
it crash if you launch

**Comment by Epic62790** [comment]
rh crack 1.3.1 is bugged af

**Comment by Jebacka** [comment]
> it crash if you launch

Nah it work for me

**Comment by Jebacka** [comment]
https://mega.nz/file/iR8EEKIJ#tmuHkr-949ymCzhLJf-_uEWHTCx9h7zFIvyjH-i7IhM
