### ISSUE TITLE
is stay a rat?

### ISSUE THREAD

**Issue by Epic62790** [Smug2f/Fast-Client-Archive#4]
it has like a hwid verificator and also in the code theres a line that says this
 try {
            Runtime.getRuntime().exec("cmd.exe /c taskkill /F /PID " + ManagementFactory.getRuntimeMXBean().getName().split("@")[0]);
         } catch (IOException var3) {
            var3.printStackTrace();
         }
i dont know what cmd.exe /c taskkill /F /PID does and i dont trust running this at all

**Comment by Smug2f** [comment]
Everything in new aspects is nor shitty nor ratted exept abstrsct

**Comment by Epic62790** [comment]
so you dont think that client thats archived aka "stay" isnt ratted besides abstract

**Comment by Smug2f** [comment]
All client in exploring new aspect are leak or crack so they got some malicious code , abstract is  open source and My friend _WMS made it it featured a good 5b corner clip so it isnt ratted

**Comment by Epic62790** [comment]
so is stay ratted

**Comment by Epic62790** [comment]
?

**Comment by Smug2f** [comment]
Yes i don't trust china client without knowing the dev
