### ISSUE TITLE
Rusherhack Rat

### ISSUE THREAD

**Issue by AGENTISNUM1** [Smug2f/Fast-Client-Archive#6]
I have done some scans on the rushercrack jar (as the source code was dmca'd). Aside from the code to take a screenshot of the desktop, some more items where flagged (Trojan.Java.GenericGBA). I am extremly safe with unknown clients, and i only run them in a linux vm. I encourage anyone who has run this to take steps to ensure that their data/computor is safe.

**Comment by AGENTISNUM1** [comment]
FileScan.IO Analysis:

Verdict: SUSPICIOUS
Confidence: 100/100
Tags: javadropper,anti-vm,html,java,vbs,xml
Domains: libdiscord-rpc.so,mcmod.info,account.name,auser.name,dc.name,dow.name,finfo.info,github.com,java.io,java.net,lgp.name,month.name,moy.name,org.apache.commons.io,os.name,other.name,sun.net,that.name,this.cx,this.cy,this.dow.name,this.month.name,this.name,userInfo.name
Hosts: 3.64.163.50,34.102.136.180,140.82.121.3,185.53.177.50,137.254.56.25,67.227.226.240,75.2.18.233,66.96.149.23,192.18.108.90,76.76.21.21,75.2.18.233

**Comment by Smug2f** [comment]
![Screenshot_20231216_083041_Opera GX](https://github.com/Smug2f/Fast-Client-Archive/assets/121037067/0ba52a90-a90c-4f0e-87ee-a5e615aab1b9)

**Comment by Smug2f** [comment]
Dont use anything that are called crack by pluto solution i only dropped it here because it's the only good crack (other crack still flag) available and also if you want i can upload rusherhack n8 who is builded but it's a way older ver

**Comment by AGENTISNUM1** [comment]
I agree that it is a great crack, and i think it is a good resource. Maybe you could add a warning beside the rushercrack link? Idk, do what u want. This archive is a great resource, and It is up to u what you do. I just wanted to make sure that people are aware of the danger. Also, I scanned some of the other plutosolutions cracks, and athough the scan might be incorrect, the Pyro Crack and the Konas Crack seem to be safe. Take that with a grain of salt tho.

**Comment by Smug2f** [comment]
added warning in descriptions 
![image](https://github.com/Smug2f/Fast-Client-Archive/assets/121037067/5faf3f2b-0e3c-4c58-85df-9c7a27087015)

**Comment by AGENTISNUM1** [comment]
looks great! love using this archive BTW, thanks for making this.

**Comment by AGENTISNUM1** [comment]
(srry i took so long to respond my internet decided not to work for 4 days)
